---
title: "World Happiness Report Dashboard"
author: "Aichen Rayphand"
format:
  dashboard:
    theme: Vapor 
nav-buttons: [github]
---

This dashboard provides visualizations on the 2024 World happiness Report (Kaggle). They portray the regional happiness levels or scores, and what impacts or effect those happiness scores.

## Row 1

```{r}
library(tidyverse)
library(plotly)
library(janitor)
library(ggplot2)

happiness <- read_csv("data/World-happiness-report-2024.csv")
Happiness <- happiness %>%
  clean_names
```

```{r, echo=FALSE}
Happiness_region <- Happiness %>%
  group_by(regional_indicator) %>%
  summarize(mean_score = mean (ladder_score, na.rm = TRUE))

p2 <- ggplot(data = Happiness_region, aes(x =reorder(regional_indicator, mean_score), y= mean_score))+
  geom_bar(stat = "identity") +
  geom_col(fill= "Purple", color= "Black") +
  labs(
    title = "Happiness score/rate by region",
    x = "Regions",
    y = "Happiness Scores"
  ) +
  theme(axis.text.x = element_text(angle = 60, vjust = .5, hjust = 1, color= "black", family= "serif"),
        axis.title = element_text(face= "bold", family = "sans", color = "plum"),
        plot.title = element_text(size = 17, face = "bold", family = "mono", hjust= 0.5),
        panel.background = element_rect(fill= "black", color = NA),
        plot.background = element_rect(fill= "lavender", color = NA))

ggplotly(p2)
```

```{r}
p2 <- ggplot(data = Happiness, aes(x= regional_indicator, y= ladder_score, fill= regional_indicator))+
  geom_boxplot() +
  labs(
    title= "Regional social support that impacts happiness levels/scores",
    x = "Regions",
    y = "Social Support",
    colour= "Happiness score"
  ) + 
  theme(axis.text.x = element_text(angle = 60, vjust = .4, hjust = 1, color= "black", family= "serif"),
        axis.title = element_text(face= "bold", family = "sans", color = "plum"),
        plot.title = element_text(size = 14, face = "bold", family = "mono", hjust= 0.1),
        panel.background = element_rect(fill= "black", color = NA),
        plot.background = element_rect(fill= "lavender", color = NA))

ggplotly(p2)
```

## World_Happiness visuals

### Plots {.tabset}

#### Happiness rates when there's freedom to make life choices

```{r, warning=FALSE}

p2 <- ggplot(data = Happiness,aes( x =freedom_to_make_life_choices, y = ladder_score, color= regional_indicator)) +
  geom_point(size= 2.5, alpha= 0.8) +
  geom_smooth (method= "lm",se= FALSE, color= "pink") +
  labs(title = "Happiness (ladder) scores when there's freedom to make life choices",
       x= "Free-will",
       y= "Happiness score",
       color= "Region") +
  theme_minimal() +
  theme(
    plot.title = element_text(face= "bold", family = "mono", size = 13, hjust= 0.2 ),
    axis.title = element_text(face= "bold", family = "sans", color = "plum"),
    panel.background = element_rect(fill= "black", color = NA),
    plot.background = element_rect(fill= "lavender", color = NA)
  )

ggplotly(p2)
```

#### Happiness rates when region has higher rates of corruption

```{r}
p2 <- ggplot(data = Happiness,aes( x =perceptions_of_corruption, y = ladder_score, color= regional_indicator)) +
  geom_point(size= 2.5, alpha= 0.8) +
  geom_smooth (method= "lm",se= FALSE, color= "pink") +
  labs(title = "Influence of corruption perceptions on happiness levels (ladder score)",
       x= "Corruption perception",
       y= "Happiness score",
       color= "Region") +
  theme_minimal() +
  theme(
    plot.title = element_text(face= "bold", family = "mono", size = 13, hjust= 0.2 ),
    axis.title = element_text(face= "bold", family = "sans", color = "plum"),
    panel.background = element_rect(fill= "black", color = NA),
    plot.background = element_rect(fill= "lavender", color = NA)
  )
  
ggplotly(p2)  

```
